apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dwk-mainapp-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: mainapp-svc
          servicePort: 2345
