apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: data-claim
      containers:
        - name: pingpong
          image: ahojukka5/dwk-pingpong:0.5
          volumeMounts:
          - name: shared-data
            mountPath: /media/shared
